// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX7_eokAbGz3sJNm0gKOXanl_d1RNf_ak',
    appId: '1:833291126249:web:061faa1f5bbe91394f7778',
    messagingSenderId: '833291126249',
    projectId: 'dark-chess-f29b9',
    authDomain: 'dark-chess-f29b9.firebaseapp.com',
    storageBucket: 'dark-chess-f29b9.firebasestorage.app',
    measurementId: 'G-8SPVVTNJ96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0BAa4d-h2QsHXjNH93vR2nhNnHuDCpPc',
    appId: '1:833291126249:android:910e3893cf5aef8b4f7778',
    messagingSenderId: '833291126249',
    projectId: 'dark-chess-f29b9',
    storageBucket: 'dark-chess-f29b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB4PeJIKC4Mrm5eVsyDTKdprDTI4T_J04',
    appId: '1:833291126249:ios:cf173977059669e24f7778',
    messagingSenderId: '833291126249',
    projectId: 'dark-chess-f29b9',
    storageBucket: 'dark-chess-f29b9.firebasestorage.app',
    iosBundleId: 'com.example.darkChess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB4PeJIKC4Mrm5eVsyDTKdprDTI4T_J04',
    appId: '1:833291126249:ios:cf173977059669e24f7778',
    messagingSenderId: '833291126249',
    projectId: 'dark-chess-f29b9',
    storageBucket: 'dark-chess-f29b9.firebasestorage.app',
    iosBundleId: 'com.example.darkChess',
  );
}
